package cmd

import (
	"fmt"
	"math"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/NETWAYS/go-check"
	"github.com/NETWAYS/go-check/result"
	"github.com/spf13/cobra"
)

type Config struct {
	Warning        string
	Critical       string
	StatusfilePath string
	MaxFileAge     int64
}

var config Config

const (
	csqPattern   = `\+CSQ:\s*(\d+),(\d+)`
	copsQuoted   = `\+COPS:\s*\d+,\d+,"([^"]*)"`
	copsUnquoted = `\+COPS:\s*\d+,\d+,([^"]+)`
	cregPattern  = `\+CREG:\s*(\d,(?:1|5))`
)

var (
	csqRe          = regexp.MustCompile(csqPattern)
	copsReQuoted   = regexp.MustCompile(copsQuoted)
	copsReUnquoted = regexp.MustCompile(copsUnquoted)
	cregRe         = regexp.MustCompile(cregPattern)
)

var rootCmd = &cobra.Command{
	Use:   "check_sms3status",
	Short: "A monitoring plugin to check the status of an SMS modem using the regular_run functionality provided in smstools3",
	Long:  `This plugin checks the status of an SMS modem using the regular_run functionality provided in smstools3a. It does not directly access the modem, but instead reads a status file generated by smstools3.`,
	Example: `
check_sms3status --warning 30 --critical 50 --statusfile /path/to/statusfile
`,
	Run: func(_ *cobra.Command, _ []string) {
		// Parse the thresholds add exit if there's an issue
		warnThreshold, warningThresholdErr := check.ParseThreshold(config.Warning)

		if warningThresholdErr != nil {
			check.ExitError(warningThresholdErr)
		}

		critThreshold, critThresholdErr := check.ParseThreshold(config.Critical)

		if critThresholdErr != nil {
			check.ExitError(critThresholdErr)
		}

		// Get the file content and info
		content, fileInfo, contentErr := getFileContentAndInfo(config.StatusfilePath)

		if contentErr != nil {
			check.ExitError(contentErr)
		}

		var overall result.Overall

		overall.AddSubcheck(checkFileAge(fileInfo))
		overall.AddSubcheck(checkContent(string(content), *warnThreshold, *critThreshold))

		check.Exit(overall.GetStatus(), overall.GetOutput())
	},
}

func Execute(version string) {
	defer check.CatchPanic()

	rootCmd.Version = version
	rootCmd.VersionTemplate()

	err := rootCmd.Execute()
	if err != nil {
		check.ExitError(err)
	}
}

func init() {
	rootCmd.Flags().StringVarP(&config.StatusfilePath, "statusfile", "s", "", "Path to the status file")
	rootCmd.Flags().StringVarP(&config.Warning, "warning", "w", "40:", "Warning threshold for signal strength in percent")
	rootCmd.Flags().StringVarP(&config.Critical, "critical", "c", "20:", "Critical threshold for signal strength in percent")
	rootCmd.Flags().Int64VarP(&config.MaxFileAge, "age", "a", 300, "The maximum age of the file in seconds (default 300)")

	_ = rootCmd.MarkFlagRequired("statusfile")
}

func Usage(cmd *cobra.Command, _ []string) {
	_ = cmd.Usage()

	os.Exit(3)
}

// getFileContentAndInfo returns the files content and file info
func getFileContentAndInfo(filePath string) ([]byte, os.FileInfo, error) {
	var fileInfo os.FileInfo

	content, contentErr := os.ReadFile(filePath)

	if contentErr != nil {
		return content, fileInfo, contentErr
	}

	fileInfo, fileInfoErr := os.Stat(filePath)
	if fileInfoErr != nil {
		return content, fileInfo, fileInfoErr
	}

	return content, fileInfo, nil
}

// checkFileAge compares the given file into with the requested maximum file age
func checkFileAge(fileInfo os.FileInfo) *result.PartialResult {
	nowSec := time.Now().Unix()
	fileSec := fileInfo.ModTime().Unix()
	fileAge := nowSec - fileSec

	tmpResult := result.NewPartialResult()

	tmpResult.SetOutput(fmt.Sprintf("Status file was last updated %d seconds ago", fileAge))
	tmpResult.SetState(check.OK)

	if fileAge > config.MaxFileAge {
		tmpResult.SetState(check.Critical)
	}

	return tmpResult
}

// checkContent compares the file content against the given thresholds
func checkContent(fileContent string, warningThreshold check.Threshold, criticalThreshold check.Threshold) *result.PartialResult {
	var signal, sigber int

	var network string

	isRegistered := true

	lines := strings.SplitSeq(fileContent, "\n")

	hasCSQ := false
	hasCREG := false
	hasCOPS := false

	for line := range lines {
		if matches := csqRe.FindStringSubmatch(line); matches != nil {
			hasCSQ = true

			val, err := strconv.Atoi(matches[1])
			if err == nil {
				signal = val
			}

			val, err = strconv.Atoi(matches[2])
			if err == nil {
				sigber = val
			}
		} else if matches := copsReQuoted.FindStringSubmatch(line); matches != nil {
			hasCOPS = true
			network = matches[1]
		} else if matches := copsReUnquoted.FindStringSubmatch(line); matches != nil {
			hasCOPS = true
			network = matches[1]
		}

		if strings.Contains(line, "+CREG:") && !cregRe.MatchString(line) {
			hasCREG = true
			isRegistered = false
		}
	}

	sigdb := (2 * signal) - 113
	sigproc := float64(signal*100) / 31.0
	result := result.NewPartialResult()

	if !hasCSQ && !hasCREG && !hasCOPS {
		result.SetOutput("Status file has incomplete structure")
		result.SetState(check.Unknown)

		return result
	}

	if !isRegistered {
		result.SetOutput("Modem not registered on network")
		result.SetState(check.Critical)

		return result
	} else if signal > 31 {
		result.SetOutput("Signal strength returned an invalid value")
		result.SetState(check.Unknown)
	}

	result.AddPerfdata(&check.Perfdata{Label: "dbm", Value: sigdb, Uom: "", Warn: nil, Crit: nil, Min: nil, Max: nil})
	result.AddPerfdata(&check.Perfdata{Label: "signal", Value: math.Round(sigproc), Uom: "%", Warn: &warningThreshold, Crit: &criticalThreshold})

	msg := fmt.Sprintf("Registered on network '%s' with signal strength %0.f%%", network, sigproc)

	result.SetOutput(msg)

	// bit error rate 99 means unknown
	if sigber != 99 {
		result.AddPerfdata(&check.Perfdata{Label: "bit_error_rate", Value: sigber})
	}

	//nolint: gocritic
	if criticalThreshold.DoesViolate(sigproc) {
		result.SetState(check.Critical)
	} else if warningThreshold.DoesViolate(sigproc) {
		result.SetState(check.Warning)
		result.SetOutput(msg)
	} else {
		result.SetState(check.OK)
	}

	return result
}
