package cmd

import (
	"fmt"
	"math"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/NETWAYS/go-check"
	"github.com/NETWAYS/go-check/result"
	"github.com/spf13/cobra"
)

var warning, critical, statusfilePath string
var maxFileAge int64

var csqRe = regexp.MustCompile(`\+CSQ:\s*(\d+),(\d+)`)
var copsReQuoted = regexp.MustCompile(`\+COPS:\s*\d+,\d+,"([^"]*)"`)
var copsReUnquoted = regexp.MustCompile(`\+COPS:\s*\d+,\d+,([^"]+)`)
var cregRe = regexp.MustCompile(`\+CREG:\s*(\d,(?:1|5))`)

var rootCmd = &cobra.Command{
	Use:   "check_sms3status",
	Short: "This plugin checks the status of an SMS modem using the regular_run functionality provided in smstools3",
	Long:  `This plugin checks the status of an SMS modem using the regular_run functionality provided in smstools3a. It does not directly access the modem, but instead reads a status file generated by smstools3.`,
	Example: `
check_sms3status --warning 30 --critical 50 --statusfile /path/to/statusfile
`,
	Run: func(_ *cobra.Command, _ []string) {
		// Parse the thresholds add exit if there's an issue
		warnThreshold, warningThresholdErr := check.ParseThreshold(warning)

		if warningThresholdErr != nil {
			check.ExitError(warningThresholdErr)
		}

		critThreshold, critThresholdErr := check.ParseThreshold(critical)

		if critThresholdErr != nil {
			check.ExitError(critThresholdErr)
		}

		// Get the file content and info
		content, fileInfo, contentErr := getFileContentAndInfo(statusfilePath)

		if contentErr != nil {
			check.ExitError(contentErr)
		}

		var overall result.Overall

		overall.AddSubcheck(checkFileAge(fileInfo))
		overall.AddSubcheck(checkContent(string(content), *warnThreshold, *critThreshold))

		check.Exit(overall.GetStatus(), overall.GetOutput())
	},
}

func Execute(version string) {
	defer check.CatchPanic()

	rootCmd.Version = version
	rootCmd.VersionTemplate()

	err := rootCmd.Execute()
	if err != nil {
		check.ExitError(err)
	}
}

func init() {
	rootCmd.Flags().StringVarP(&statusfilePath, "statusfile", "s", "", "Path to the status file")
	rootCmd.Flags().StringVarP(&warning, "warning", "w", "40:", "Warning threshold for signal strength in percent")
	rootCmd.Flags().StringVarP(&critical, "critical", "c", "20:", "Critical threshold for signal strength in percent")
	rootCmd.Flags().Int64VarP(&maxFileAge, "age", "a", 300, "The maximum age of the file in seconds (default 300)")

	_ = rootCmd.MarkFlagRequired("statusfile")
}

func Usage(cmd *cobra.Command, _ []string) {
	_ = cmd.Usage()

	os.Exit(3)
}

// getFileContentAndInfo returns the files content and file info
func getFileContentAndInfo(filePath string) ([]byte, os.FileInfo, error) {
	content, contentErr := os.ReadFile(filePath)

	var fileInfo os.FileInfo

	if contentErr != nil {
		return content, fileInfo, contentErr
	}

	fileInfo, fileInfoErr := os.Stat(filePath)
	if fileInfoErr != nil {
		return content, fileInfo, fileInfoErr
	}

	return content, fileInfo, nil
}

// checkFileAge compares the given file into with the requested maximum file age
func checkFileAge(fileInfo os.FileInfo) *result.PartialResult {
	nowSec := time.Now().Unix()
	fileSec := fileInfo.ModTime().Unix()
	fileAge := nowSec - fileSec

	tmpResult := &result.PartialResult{
		Output: fmt.Sprintf("Status file was last updated %d seconds ago", fileAge),
	}

	tmpResult.SetState(check.OK)

	if fileAge > maxFileAge {
		tmpResult.SetState(check.Critical)
	}

	return tmpResult
}

// checkContent compares the file content against the given thresholds
func checkContent(fileContent string, warningThreshold check.Threshold, criticalThreshold check.Threshold) *result.PartialResult {
	var signal, sigber int

	var network string

	isRegistered := true

	lines := strings.SplitSeq(fileContent, "\n")

	for line := range lines {
		if matches := csqRe.FindStringSubmatch(line); matches != nil {
			val, err := strconv.Atoi(matches[1])
			if err == nil {
				signal = val
			}

			val, err = strconv.Atoi(matches[2])
			if err == nil {
				sigber = val
			}
		} else if matches := copsReQuoted.FindStringSubmatch(line); matches != nil {
			network = matches[1]
		} else if matches := copsReUnquoted.FindStringSubmatch(line); matches != nil {
			network = matches[1]
		}

		if strings.Contains(line, "+CREG:") && !cregRe.MatchString(line) {
			isRegistered = false
		}
	}

	sigdb := (2 * signal) - 113
	sigproc := float64(signal*100) / 31.0
	result := result.NewPartialResult()

	if !isRegistered {
		result.Output = "Modem not registered on network"
		result.SetState(check.Critical)

		return result
	} else if signal > 31 {
		result.Output = "Signal strength returned an invalid value"
		result.SetState(check.Unknown)
	}

	result.Perfdata.Add(&check.Perfdata{Label: "dbm", Value: sigdb, Uom: "", Warn: nil, Crit: nil, Min: nil, Max: nil})
	result.Perfdata.Add(&check.Perfdata{Label: "signal", Value: math.Round(sigproc), Uom: "%", Warn: &warningThreshold, Crit: &criticalThreshold})

	msg := fmt.Sprintf("Registered on network '%s' with signal strength %0.f%%", network, sigproc)

	result.Output = msg

	// bit error rate 99 means unknown
	if sigber != 99 {
		result.Perfdata.Add(&check.Perfdata{Label: "bit_error_rate", Value: sigber})
	}

	//nolint: gocritic
	if criticalThreshold.DoesViolate(sigproc) {
		result.SetState(check.Critical)
	} else if warningThreshold.DoesViolate(sigproc) {
		result.SetState(check.Warning)
		result.Output = msg
	} else {
		result.SetState(check.OK)
	}

	return result
}
